/* 14 Задание */

SELECT * FROM t_inprice;
SELECT * FROM t_group; 

/* 15 Задание */

SELECT id_material, name FROM t_material;

/* 16 Задание */

SELECT surname, name, father_name, birthdate FROM t_employer; 

/* 17 Задание */

SELECT * FROM t_employer WHERE father_name = 'M';

/* 18 Задание */

SELECT * FROM t_caterer
  WHERE id_caterer IN
  (SELECT id_caterer FROM t_supply
  WHERE supply_date >='01.04.2009'
   AND supply_date <='30.06.2009'); 

/* 19 Задание */

SELECT * FROM t_section
  WHERE id_section IN
  (SELECT id_section FROM t_deliver 
  WHERE  deliver_date >='01.08.2009'
   AND deliver_date <='31.08.2009');

/* 20 Задание */

SELECT name FROM t_section
  WHERE id_section IN
  (SELECT id_section FROM t_deliver
  WHERE deliver_date = SYSDATE);

/* 21 Задание */

SELECT name FROM t_material
  WHERE id_material IN
  (SELECT id_material FROM t_supply
  WHERE supply_date >= '01.01.2017'
  AND supply_date <= SYSDATE);

/* 22 Задание */

SELECT name FROM t_material
  WHERE id_material NOT IN
  (SELECT id_material FROM t_supply 
  WHERE supply_date >= '01.01.2017'
   AND supply_date <= SYSDATE)
  AND id_material IN
  (SELECT id_material FROM t_surplus
  WHERE VOLUME LIKE 0);

/* 23 Задание */

SELECT t_section.id_section, t_section.name, t_employer.surname, t_employer.name, t_employer.father_name
  FROM t_section, t_employer
  WHERE t_section.id_employer = t_employer.id_employer;

/* 24 Задание */

SELECT T_SECTION.ID_SECTION, T_SECTION.NAME, T_EMPLOYER.SURNAME, T_EMPLOYER.NAME, T_EMPLOYER.FATHER_NAME
  FROM T_SECTION, T_EMPLOYER
  WHERE T_SECTION.ID_EMPLOYER = T_EMPLOYER.ID_EMPLOYER;

/* 25 Задание */

SELECT tc.NAME, tm.NAME, ts.VOLUME, ti.PRICE 
  FROM T_CATERER tc, T_MATERIAL tm, T_SUPPLY ts, T_INPRICE ti 
  WHERE tc.ID_CATERER = ts.ID_CATERER 
  AND tm.ID_MATERIAL = ts.ID_MATERIAL 
  AND ti.ID_MATERIAL = tm.ID_MATERIAL 
  AND ts.SUPPLY_DATE BETWEEN '01.01.2009' AND '31.03.2009';

/* 26 Задание */

SELECT tc.NAME, tm.NAME, ts.VOLUME, ti.PRICE 
  FROM T_CATERER tc, T_MATERIAL tm, T_SUPPLY ts, T_INPRICE ti 
  WHERE tc.ID_CATERER = ts.ID_CATERER 
  AND tm.ID_MATERIAL = ts.ID_MATERIAL 
  AND ti.ID_MATERIAL = tm.ID_MATERIAL 
  AND ts.SUPPLY_DATE BETWEEN '01.01.2009' AND '31.03.2009' AND tc.ACTUAL_ADDRESS LIKE '%Пермь%';

/*27 Задание */

SELECT tm.NAME, ts.VOLUME, ts1.NAME 
  FROM T_MATERIAL tm, T_SUPPLY ts, T_STORE ts1 
  WHERE tm.ID_MATERIAL = ts.ID_MATERIAL AND ts1.ID_STORE = ts.ID_STORE;

/*28 Задание */

SELECT tc.NAME, tm.NAME, ts.VOLUME, ti.PRICE, ts.SUPPLY_DATE
  FROM T_CATERER tc 
  JOIN T_MATERIAL tm ON tc.ID_CATERER IN
  (SELECT ID_CATERER FROM T_SUPPLY ts WHERE SUPPLY_DATE BETWEEN '01.01.2009' AND '31.03.2009')
  JOIN T_SUPPLY ts ON ts.ID_MATERIAL = tm.ID_MATERIAL AND ts.ID_CATERER = tc.ID_CATERER
  JOIN T_INPRICE ti ON ti.ID_MATERIAL = tm.ID_MATERIAL;

/* 29 Задание */

SELECT tc.NAME, tm.NAME, ts.VOLUME, ti.PRICE, ts.SUPPLY_DATE
  FROM T_CATERER tc 
  LEFT JOIN T_SUPPLY ts ON ts.ID_CATERER = tc.ID_CATERER
  LEFT JOIN T_MATERIAL tm ON ts.ID_MATERIAL = tm.ID_MATERIAL
  LEFT JOIN T_INPRICE ti ON ti.ID_MATERIAL = tm.ID_MATERIAL;

/* 30 Задание */

SELECT ts.ID_STORE, ts.NAME, tm.NAME, ts1.VOLUME
  FROM T_STORE ts LEFT JOIN T_SURPLUS ts1 ON ts.ID_STORE = ts1.ID_STORE
  LEFT JOIN T_MATERIAL tm ON tm.ID_MATERIAL = ts1.ID_MATERIAL;

/* 31 Задание */

SELECT tm1.NAME, tm.ID_MATERIAL, tm.NAME, ti.PRICE
  FROM T_MATERIAL tm JOIN T_MEASURE tm1 ON tm.ID_MEASURE = tm1.ID_MEASURE
  JOIN T_INPRICE ti ON ti.ID_MATERIAL = tm.ID_MATERIAL AND ti.PRICE_DATE IN
    (SELECT PRICE_DATE FROM T_INPRICE 
       WHERE PRICE_DATE BETWEEN '01.07.2009' AND '30.09.2009');

/* 32 Задание */

SELECT tm1.NAME, tm.ID_MATERIAL, tm.NAME, ti.PRICE
  FROM T_MATERIAL tm LEFT JOIN T_MEASURE tm1 ON tm.ID_MEASURE = tm1.ID_MEASURE
  LEFT JOIN T_INPRICE ti ON ti.ID_MATERIAL = tm.ID_MATERIAL;

/* 33 Задание */

ALTER TABLE T_EMPLOYER
  ADD id_manager INT;
UPDATE T_EMPLOYER
  SET ID_MANAGER = 1
    WHERE ID_EMPLOYER BETWEEN 2 AND 4;
UPDATE T_EMPLOYER
  SET ID_MANAGER = 5
    WHERE ID_EMPLOYER LIKE 1;

/* 34 Задание */

ALTER TABLE T_GROUP
  ADD NEW_GROUP INT;
UPDATE T_GROUP
  SET NEW_GROUP = 1
    WHERE ID_GROUP BETWEEN 1 AND 5;
UPDATE T_GROUP
  SET MINI_GROUP = 2
    WHERE ID_GROUP < 3;
UPDATE T_GROUP
  SET MINI_GROUP = 3
    WHERE ID_GROUP > 3;

/* 35 Задание */

CREATE TABLE T_Exemp (
  ID_EMPLOYER INT NOT NULL,
  SURNAME VARCHAR2(30) NOT NULL,
  NAME VARCHAR2(30) NOT NULL,
  FATHER_NAME VARCHAR2(30) NOT NULL,
  SEX CHAR,
  BIRTHDATE DATE,
  ID_MANAGER INT,
  ID_JOB INT,
  CONSTRAINT pk_exemp PRIMARY KEY (ID_EMPLOYER)
  );
INSERT INTO T_EXEMP (ID_EMPLOYER, SURNAME, NAME, FATHER_NAME, BIRTHDATE, ID_MANAGER, ID_JOB)
  VALUES (seq_employer.NEXTVAL, 'Фамилия', 'Имя', 'Отчество', '15.14.2000', 1, 1);
INSERT INTO T_EXEMP (ID_EMPLOYER, SURNAME, NAME, FATHER_NAME, BIRTHDATE, ID_MANAGER, ID_JOB)
  VALUES (seq_employer.NEXTVAL, 'Фамилия1', 'Имя1', 'Отчество1', '15.14.2001', 2, 2);
INSERT INTO T_EXEMP (ID_EMPLOYER, SURNAME, NAME, FATHER_NAME, BIRTHDATE, ID_MANAGER, ID_JOB)
  VALUES (seq_employer.NEXTVAL, 'Фамилия2', 'Имя2', 'Отчество2', '15.14.2002', 3, 3);

/* 36 Задание */
  
ALTER TABLE T_EXEMP
  ADD DISMISSED DATE;
UPDATE T_EXEMP
  SET DISMISSED = '12.12.2012'; 

/* 37 Задание */

CREATE TABLE T_Contact (
  ID_CONTACT INT NOT NULL,
  ID_CATERER INT,
  SURNAME NVARCHAR2(20) NOT NULL,
  NAME NVARCHAR2(20) NOT NULL,
  FATHER_NAME NVARCHAR2(30),
  PHONE NUMBER(11) NOT NULL,
  CONSTRAINT PK_Contact PRIMARY KEY (ID_CONTACT),
  CONSTRAINT FK_Contact_Caterer
    FOREIGN KEY (ID_CATERER) REFERENCES T_CATERER(ID_CATERER) ON DELETE CASCADE
);
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, SURNAME, NAME, FATHER_NAME, PHONE)
  VALUES (1, 1, 'Рылок', 'Василий', 'Петрович', '89124565367');
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, SURNAME, NAME, FATHER_NAME, PHONE)
  VALUES (2, 2, 'Крылов', 'Андрей', 'Сергеевич', '89508536785');
INSERT INTO T_CONTACT (ID_CONTACT, ID_CATERER, SURNAME, NAME, FATHER_NAME, PHONE)
  VALUES (3, 3, 'Мальков', 'Альберт', 'Викторович', '89384561468');

/* 38 Задание */ 


SELECT * FROM T_CATERER
  ORDER BY NAME;

/* 39 Задание */

SELECT * FROM T_CATERER tc JOIN T_CONTACT tc1
  ON tc.ID_CATERER = tc1.ID_CATERER
  ORDER BY tc.NAME, tc1.SURNAME, tc1.NAME, tc1.FATHER_NAME;

/* 40 Задание */

SELECT ts.NAME, tm.NAME, ts1.VOLUME
  FROM T_STORE ts LEFT JOIN T_SURPLUS ts1  ON ts.ID_STORE = ts1.ID_STORE
  LEFT JOIN T_MATERIAL tm ON tm.ID_MATERIAL = ts1.ID_MATERIAL
  ORDER BY ts1.VOLUME DESC;

/* 41 Задание */

SELECT tm.NAME AS "material", tc.NAME AS "caterer", SUM(ts.VOLUME) AS "volume"
  FROM T_CATERER tc JOIN T_SUPPLY ts ON tc.ID_CATERER = ts.ID_CATERER
  JOIN T_MATERIAL tm ON tm.ID_MATERIAL = ts.ID_MATERIAL
  WHERE ts.SUPPLY_DATE BETWEEN '01.01.2017' AND SYSDATE
  GROUP BY tm.NAME, tc.NAME
  ORDER BY tc.NAME, tm.NAME;

/* 42 Задание */

SELECT tm.NAME AS "material", AVG(ts.VOLUME * ti.PRICE) AS "sr"
  FROM T_MATERIAL tm LEFT JOIN T_SUPPLY ts ON tm.ID_MATERIAL = ts.ID_MATERIAL
  LEFT JOIN T_INPRICE ti ON tm.ID_MATERIAL = ti.ID_MATERIAL
  WHERE ts.SUPPLY_DATE BETWEEN '01.01.2017' AND SYSDATE
  GROUP BY tm.NAME
  ORDER BY tm.NAME;

/* 43 Задание */

SELECT tm.NAME AS "material", SUM(ts.VOLUME) AS "summa"
  FROM T_MATERIAL tm LEFT JOIN T_SUPPLY ts ON tmL.ID_MATERIAL = ts.ID_MATERIAL
  WHERE ts.SUPPLY_DATE BETWEEN '01.01.2017' AND SYSDATE
  GROUP BY tm.NAME
  ORDER BY tm.NAME;

/* 45 Задание */

SELECT NAME FROM T_STORE ts INNER JOIN T_SURPLUS ts1
  ON ts.ID_STORE = ts1.ID_STORE
  GROUP BY NAME HAVING SUM(VOLUME) = 0;

/* 46 Задание */

SELECT NAME FROM T_CATERER tc INNER JOIN T_SUPPLY ts
  ON tc.ID_CATERER = ts.ID_CATERER
  WHERE SUPPLY_DATE BETWEEN '01.01.2017' AND  SYSDATE
  GROUP BY NAME HAVING SUM(VOLUME) < 1000

/* 47 Задание */

SELECT NAME FROM T_CATERER tc JOIN T_SUPPLY ts
  ON tc.ID_CATERER = ts.ID_CATERER
  WHERE SUPPLY_DATE BETWEEN '01.01.2017' AND SYSDATE
  GROUP BY NAME HAVING SUM(VOLUME) = MAX(VOLUME)


